site_name: ALL-AI-THINGS

#--------------all-ai-things-navigation-setup--------------------------------------------------
nav: 
  - Home: index.md

  # AI Tools
  - AI-Tools: 
    - Code-Generation: ai-tools/code-gen.md
    - Text-generation: ai-tools/list-of-models.md
    - Audio-Video-Generation: ai-tools/audio-video-gen.md

  # Models Related Docs
  - Models: 
    - Models-Hub: models/models.md
    - Models: ai-tools/list-of-models.md

  # Prompts Lists
  - Prompts: 
    - MidJourney-Prompts: prompts/midjourney-prompts.md
    - Stable-Diffusion-Prompts: prompts/sd-promts.md
    - Coding-Prompts: prompts/code-prompts.md


#---------------------------------------------------------------
# Themes related code

# theme: lux
# # site_favicon: favicon.ico
# # site_favicon: site-favicon.ico

# theme: dracula
# # site_favicon: favicon.ico

# theme: pulse
# # site_favicon: favicon.ico

theme: 
  name: material
  palette:
    # scheme: default
    scheme: slate
    primary: indigo
  # features:
  #   - navigation.footer    
  copyright: Copyright &copy; 2023 rxc3050  
